name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
  publish-windows:
    runs-on: windows-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Publish
      run: dotnet publish -p:PublishTrimmed=true --self-contained --runtime win-x86 -c Release -o dist/win-x86
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: win-x86
        path: dist/win-x86
      
  publish-linux:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Publish
      run: dotnet publish -p:PublishTrimmed=true --self-contained --runtime linux-x64 -c Release -o dist/linux-x64
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: linux-x64
        path: dist/linux-x64
        
  publish-macos:
    runs-on: macos-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Publish
      run: dotnet publish -p:PublishTrimmed=true --self-contained --runtime osx-x64 -c Release -o dist/macos-x64
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: macos-x64
        path: dist/macos-x64
        
  create-release:
    runs-on: ubuntu-latest
    needs: |
      publish-windows
      publish-mac
      publish-linux
    
    steps:
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v2
